spring:
  application:
    name: expenses-service
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: none
  jackson:
    serialization:
      write_dates_as_timestamps: false
server:
  port: 9191